### ISSUE TITLE
pia-wg-netns

### ISSUE THREAD

**Issue by nbanb** [nurupo/pia-wg-netns-vpn#1]
Dear nurupo

It seems to be a nice job !
I just send you an email, your hosted by GMAIL, please check your spams 

Kind regards,
nbanba (https://github.com/nbanb/pia-wg-netns)

**Comment by nurupo** [comment]
Yep, got it, thanks. It did indeed go into Spam, wouldn't have noticed it if you haven't let a comment here.
Thanks for letting me know of your script.
